version: '2'
services:
  animal_certification-app:
    image: animal_certification
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://animal_certification-postgresql:5432/Animal_Certification
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  animal_certification-postgresql:
    extends:
      file: postgresql.yml
      service: animal_certification-postgresql
