version: '2'
services:
  animal_certification-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/Animal_Certification/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Animal_Certification
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
